apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: django-app
data:
  DJANGO_SETTINGS_MODULE: web.settings
  ALLOWED_HOSTS: '["0.0.0.0", "127.0.0.1", "kubernetes-django.com"]'
  